before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: RuyVcNQCXWpD4OkfNvfu9HMM9aDGU5/Xv/JX7VfZ6mJemtw0oh6KWwUJSq0ggCqrtR1FU3a81QQ0MxerjjB2imwrvRRjwQbRs2z2GnIpWE00JSdecdIQJ3+s+MFDbn1TwSQn5mfTfAxoLN4bSs4HviwCSeo7US3cj+J8ZkwHzzW8UNPLApIH4MbbZqNZBjCz6Ho5DsLes2WnS6nVLbEm8Zud3DE9fSE3qWjx5nET6y+YnYHouj5GW/Hpu9hjke/a0d8/mJBngFZ/WvuwD88EdEEX3QoD59Wh405rM2dou21GxkXquh8N4wT5uNAO/vOr38tM2T78Fb2W9UqzwYxa4LDAZ83GVJPUBkV+b++h8aClfuxAeno6DZYwdHMOos09NI/7pgQVl2AswBG7GJzK24Tx/GsPXLV3Q3QyTlXFVv/m7hDuR01JkQzHA+yAY/pEeomEAg1PF7wvXx044WGQyxQR9+mQoF4tHYtJFGxtkSPBad7kKBEWi5TISlO/P3SVyWVWG6iMyjCS+2aQ03NVdbPEPXP2As80W+boZusvwNKsFR9JJdzODyD2RFr8+cg1G8VQwso98zNYit/PRaF2NFRHWWDccq1Ry0TUbD6YxGFDJvCFak5Mu1nk1E1H4sbBNenScaCx/yJLRZ6jqhbjVRKFVrZk7Lj1ee2F085Sz8E= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
